services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  postgresql_data:
